---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - frontend.yaml
  - infrastructure.yaml
  
patches:
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=booking-microservices
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: github }]
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 60
